### ISSUE TITLE
火绒已杀

### ISSUE THREAD

**Issue by WilliamL71Oi** [coleak2021/evilhiding#2]
![图片](https://github.com/coleak2021/evilhiding/assets/37209194/ed28f7d4-778c-46b4-a4f7-a5858f4fa387)

**Comment by coleak2021** [comment]
马上测试，稍等

**Comment by coleak2021** [comment]
<img width="751" alt="image" src="https://github.com/coleak2021/evilhiding/assets/103516488/378b7d48-3da7-4314-b44e-b1ed12e5d905">
<img width="1280" alt="image" src="https://github.com/coleak2021/evilhiding/assets/103516488/21577c03-3448-454e-adb1-0893733c8be4">

**Comment by coleak2021** [comment]
测试后没有问题，可以使用最新版本的cs试试，可能是cs版本不一样导致的
